kind: pipeline
type: docker
name: default

steps:
- name: test-and-build
  image: rust:slim-buster
  commands:
  - apt update && apt install -y llvm-dev libclang-dev linux-libc-dev clang
  - rustup component add clippy rustfmt
  - cargo fmt --check
  - cargo clippy --release -- -D warnings
  - cargo build --release

- name: publish
  image: plugins/docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    repo: registry.local:5000/puuuh/wireguard-ext
    username: puuuh
    password: p25*CXhlp74O
    insecure: true
      
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
