kind: pipeline
type: docker
name: default

steps:
- name: test-and-build
  image: rust:slim-buster
  commands:
  - apt update && apt install -y llvm-dev libclang-dev linux-libc-dev clang
  - rustup component add clippy rustfmt
  - cargo fmt --check
  - cargo clippy --release -- -D warnings
  - cargo build --release

- name: publish
  image: alpine:latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - apt add docker
  - echo "{\"insecure-registries\" : [ \"registry.local:5000\" ]}" > /etc/docker/daemon.json
  - docker build -t registry.local:5000/puuuh/wireguard-ext:latest .
  - docker push registry.local:5000/puuuh/wireguard-ext:latest --insecure
  - docker rmi registry.local:5000/puuuh/wireguard-ext:latest
      
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
