kind: pipeline
type: docker
name: default

steps:
- name: test-and-build
  image: rust:slim-buster
  commands:
  - apt update && apt install -y llvm-dev libclang-dev linux-libc-dev clang
  - rustup component add clippy
  - cargo clippy --release
  - cargo build --release

- name: publish
  image: plugins/docker
  settings:
    repo: puuuh/wireguard-ext
    username: puuuh
    password: p25*CXhlp74O
