kind: pipeline
type: docker
name: default

steps:
- name: test-and-build
  image: rust:slim-buster
  commands:
  - apt update && apt install -y llvm-dev
  - rustup component add clippy
  - cargo clippy
  - cargo build --release
