kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone DRONE_REPO_LINK .
  - git checkout $DRONE_COMMIT

- name: test
  image: rust:slim-buster
  commands:
  - rustup add component clippy
  - cargo clippy
  - cargo build --release
